### ISSUE TITLE
Misa

### ISSUE THREAD

**Issue by MisaSvarickova** [PyLadiesCZ/TestLadies#8]
![image](https://cloud.githubusercontent.com/assets/25110281/21954040/2392f040-da47-11e6-8345-c63d1343d03c.png)

**Comment by vasekch** [comment]
ajaj, tohle melo byt do jineho repozitare :) 
https://github.com/PyLadiesCZ/TestLadiesSandbox

**Comment by MisaSvarickova** [comment]
Vim, prisla jsem na to zahy a posleze provedla jiz korektne. Zdanlive se tedy muze jevit, ze mam pomalejsi reakce nez servirka v nadraznim bufetu :-)
